### ISSUE TITLE
How can i override the theme?

### ISSUE THREAD

**Issue by RonnieDuck** [loilo/vscode-snazzy-light#1]
i tried the following, but it didn't work.
"editor.tokenColorCustomizations": {
  "[Snazzy Light]": [
    {
      "scope": ["storage.type"],
      "settings": {
        "foreground": "#9466ff",
        "fontStyle": "italic"
      }
    }
  ]
}

**Comment by loilo** [comment]
Huh. Sorry, I really overlooked this issue. 😕 

In case you've not figured it out yourself by now: You're missing one layer of configuration. The array of overrides is not the direct value of `[Snazzy Light]` but a value of its `textMateRules` property.

So in your case, that would be:
```js
"editor.tokenColorCustomizations": {
	"[Snazzy Light]": {
		"textMateRules": [ // <- you missed this level
			{
				"scope": ["storage.type"],
				"settings": {
					"foreground": "#9466ff",
					"fontStyle": "italic"
				}
			}
		]
    }
}
```

**Comment by RonnieDuck** [comment]
@loilo Hi, I found the color didn't change in different scope after setting "storage.type", see below:
![image](https://user-images.githubusercontent.com/19317133/62181918-77994100-b387-11e9-9803-07e879087900.png)

Can I paste the code(/themes/Snazzy-Light-color-theme.json) into my setting.json?
If I can, which scope should it be put in?

**Comment by loilo** [comment]
I'm not sure whether you can put it entirely into you `settings.json`, I don't see a reason it should not work — you may get in trouble having conflicts with your active theme though. (Why would you want to do that anyway?)

Regarding your first question: If an overridden scope didn't change, it's usually a problem of too low specificity. To debug this, you can put the cursor at the position that you want to re-color and execute the VS Code command "Developer: Inspect TM Scopes".

It looks like this:

![Screenshot of VS Code's scope inspection feature](https://user-images.githubusercontent.com/1922624/62188145-d355d100-b36b-11e9-9406-dd441e5c3de5.png)

As you can see, the applied scope for the `class` keyword here is `meta.class storage.type` — this is more specific than `storage.type`, therefore you cannot override it with a single `storage.type` override, you'd have to override it specifically with the `meta.class storage.type` scope (or some other more specific scope).
