### ISSUE TITLE
Directories and package names in the integrated terminal are not visible against the background

### ISSUE THREAD

**Issue by lao-gan-man** [loilo/vscode-snazzy-light#2]
It seems that the colour of directories and package names is set to a very light colour which makes them all but invisible. Sorry if this has an easy fix but I thought I'd report it since I assume this to be the default setting on this colour theme.

**Comment by loilo** [comment]
Hey @Bobik808, sorry for getting back to you so late, somehow overlooked this issue.

I'm afraid I'm not sure which area you refer to exactly, would you mind taking a screenshot and attaching it here? 🙏
