### ISSUE TITLE
Status bar background color?

### ISSUE THREAD

**Issue by ngekoding** [loilo/vscode-snazzy-light#5]
Is it possible to change the status bar background color?

**Comment by loilo** [comment]
I like the status bar background color as it currently is, so I won't change it in the theme.

However, you can easily adjust it to whatever you like in your VSCode settings:

1. Open your `settings.json` ("Preferences: Open Settings (JSON)" in the command palette)
2. Add the following configuration:

   ```json
   "workbench.colorCustomizations": {
     "[Snazzy Light]": {
       "statusBar.noFolderBackground": "#565869",
       "statusBarItem.remoteBackground": "#238744",
       "statusBar.background": "#2DAE58",
       "statusBar.debuggingBackground": "#13BBB7",
       "statusBar.debuggingBorder": "#00A39F"
     }
   }
   ```
3. Adjust the colors to your needs.

   - `statusBar.noFolderBackground` is the grey background when no folder is open.

     <img width="170" height="95" alt="screenshot of status bar with no folder opened" src="https://user-images.githubusercontent.com/1922624/139842343-d6d116ef-4a02-4a34-ace7-a3eef18bac93.png">

   - `statusBarItem.remoteBackground` is the dark-ish green background behind the button on the left of the bar.

     <img width="170" height="95" alt="screenshot of status bar with no folder opened" src="https://user-images.githubusercontent.com/1922624/139842343-d6d116ef-4a02-4a34-ace7-a3eef18bac93.png">

   - `statusBar.background` is the default green background when any folder is open.

     <img width="170" height="95" alt="screenshot of status bar folder opened" src="https://user-images.githubusercontent.com/1922624/139842765-b619d81c-bfbb-4bc5-88e4-0c53d5bf5fce.png">

   - `statusBar.debuggingBackground` is the teal background and `statusBar.debuggingBorder` is the color of the status bar border for a VSCode window in debugging mode.

     <img width="170" height="95" alt="screenshot of status bar in a debugging window" src="https://user-images.githubusercontent.com/1922624/139843242-8e89e7ce-e168-4aac-a696-5fdad388ae6c.png">

I hope this helped. Sorry for coming back to you so late, seems like I accidentally turned off the repository's notifications...

**Comment by ngekoding** [comment]
Thank you, it is very helpful and detail. I will try as soon as possible.
