### ISSUE TITLE
has a plan to prot the theme to Jetbrains?

### ISSUE THREAD

**Issue by yangxu52** [loilo/vscode-snazzy-light#7]
I really like the theme in vscode. It preter vivid and bright. 
I mainly work in front-end development in vscode. But I am trying transfer use WebStorm now.
Jetbrains's Linght thme's color scheme is too ancient, like console color scheme. 
I don't know how to prot. sry.

**Comment by loilo** [comment]
I don't use WebStorm (anymore), so I have no plans to port the theme.
That said, I had ported it a couple years ago when I still used PHPStorm, although in a very barebones way. You can find that version of the theme [in this gist](https://gist.github.com/loilo/4d95341e499fff6b5388c9811da7fe28), maybe you can make some use of it.

**Comment by yangxu52** [comment]
Thanks.
